# Every time a push is made to the reference_guide.mmd flowchart, convert to png (sphinx mermaid breaks everything) 

name: mermaid_flowchart_to_png

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
        # only watch the following files
        - source/reference_guide/reference_flowchart.mmd

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# jobs to rin
jobs:
  
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@v1
      - name: Convert from mmd to png
        run: |
          npm install @mermaid-js/mermaid-cli
          ./node_modules/.bin/mmdc -i ./source/reference_guide/reference_flowchart.mmd -o ./source/reference_guide/reference_flowchart.png 
      - name: commit changes
        run: |
          git config --local user.name "kitbenjamin"
          git status
          git add source/reference_guide/reference_flowchart.png
          git commit -m "Auto converting reference_flowchart to png"
      - name: push changes 
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: main
