# Every time a push is made to the reference_guide.mmd flowchart, convert to png (sphinx mermaid breaks everything) 

name: mermaid_flowchart_to_png

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
        # only watch the following files
        - source/reference_guide/reference_flowchart.mmd

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# jobs to rin
jobs:
  
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install @mermaid-js/mermaid-cli
      - run: pwd
      - run: ls
      - run: ./node_modules/.bin/mmdc -i ./source/reference_guide/reference_flowchart.mmd -o ./source/reference_guide/reference_flowchart.png
      - run: ls ./source/reference_guide/*
      - run: git add .
      - run: git commit -m "Auto updating reference_flowchart to png"
      - run: git push origin master
